package discovery

import (
	"reflect"
	"testing"
)

const testSource = "crontab:/etc/cron.d/sample"

func TestCronParser(t *testing.T) {
	tests := []struct {
		name   string
		format crontabFormat
		user   string
		lines  []string
		want   []Entry
	}{
		{
			name:   "a system line names the user between the schedule and the command",
			format: systemFormat,
			lines:  []string{"17 *\t* * *\troot\tcd / && run-parts --report /etc/cron.hourly"},
			want: []Entry{{
				Source: testSource, Raw: "17 *\t* * *\troot\tcd / && run-parts --report /etc/cron.hourly",
				Schedule: "17 * * * *", ScheduleKind: KindCron, Command: "cd / && run-parts --report /etc/cron.hourly", User: "root",
			}},
		},
		{
			name:   "a user crontab runs as the user the file is named after",
			format: userFormat,
			user:   "deploy",
			lines:  []string{"*/10 * * * * cd /srv/app && ./bin/queue-tick"},
			want: []Entry{{
				Source: testSource, Raw: "*/10 * * * * cd /srv/app && ./bin/queue-tick",
				Schedule: "*/10 * * * *", ScheduleKind: KindCron, Command: "cd /srv/app && ./bin/queue-tick", User: "deploy",
			}},
		},
		{
			name:   "a shorthand stands in for the five fields",
			format: userFormat,
			user:   "root",
			lines:  []string{"@reboot /usr/local/bin/warm-cache"},
			want: []Entry{{
				Source: testSource, Raw: "@reboot /usr/local/bin/warm-cache",
				Schedule: "@reboot", ScheduleKind: KindCron, Command: "/usr/local/bin/warm-cache", User: "root",
			}},
		},
		{
			name:   "names and ranges are read as cron reads them",
			format: userFormat,
			user:   "root",
			lines:  []string{"0 0 1 jan-mar mon-fri,sat /usr/local/bin/quarterly"},
			want: []Entry{{
				Source: testSource, Raw: "0 0 1 jan-mar mon-fri,sat /usr/local/bin/quarterly",
				Schedule: "0 0 1 jan-mar mon-fri,sat", ScheduleKind: KindCron, Command: "/usr/local/bin/quarterly", User: "root",
			}},
		},
		{
			name:   "a timezone applies to the lines below it, not the ones above",
			format: userFormat,
			user:   "root",
			lines:  []string{"0 1 * * * /usr/local/bin/before", "CRON_TZ=Europe/Lisbon", "0 2 * * * /usr/local/bin/after"},
			want: []Entry{
				{Source: testSource, Raw: "0 1 * * * /usr/local/bin/before", Schedule: "0 1 * * *", ScheduleKind: KindCron, Command: "/usr/local/bin/before", User: "root"},
				{Source: testSource, Raw: "0 2 * * * /usr/local/bin/after", Schedule: "0 2 * * *", ScheduleKind: KindCron, Timezone: "Europe/Lisbon", Command: "/usr/local/bin/after", User: "root"},
			},
		},
		{
			name:   "TZ sets the timezone too",
			format: userFormat,
			user:   "root",
			lines:  []string{"TZ = 'UTC'", "0 2 * * * /usr/local/bin/after"},
			want: []Entry{{
				Source: testSource, Raw: "0 2 * * * /usr/local/bin/after",
				Schedule: "0 2 * * *", ScheduleKind: KindCron, Timezone: "UTC", Command: "/usr/local/bin/after", User: "root",
			}},
		},
		{
			name:   "blank lines, comments and other assignments describe no work",
			format: userFormat,
			user:   "root",
			lines:  []string{"", "   ", "# DO NOT EDIT THIS FILE", `MAILTO=""`, "SHELL=/bin/sh", "PATH=/usr/bin:/bin"},
			want:   nil,
		},
		{
			name:   "the command stops at an unescaped percent sign and keeps an escaped one",
			format: userFormat,
			user:   "root",
			lines:  []string{`0 5 * * * /usr/bin/mail -s 100\% done ops%body line%second line`},
			want: []Entry{{
				Source: testSource, Raw: `0 5 * * * /usr/bin/mail -s 100\% done ops%body line%second line`,
				Schedule: "0 5 * * *", ScheduleKind: KindCron, Command: "/usr/bin/mail -s 100% done ops", User: "root",
			}},
		},
		{
			name:   "a leading hyphen only asks cron not to log the job",
			format: systemFormat,
			lines:  []string{"-*/5 * * * * root /usr/local/bin/quiet"},
			want: []Entry{{
				Source: testSource, Raw: "-*/5 * * * * root /usr/local/bin/quiet",
				Schedule: "*/5 * * * *", ScheduleKind: KindCron, Command: "/usr/local/bin/quiet", User: "root",
			}},
		},
		{
			name:   "an entry that runs the agent is marked",
			format: systemFormat,
			lines:  []string{"@daily root /usr/local/bin/omj-agent discover"},
			want: []Entry{{
				Source: testSource, Raw: "@daily root /usr/local/bin/omj-agent discover",
				Schedule: "@daily", ScheduleKind: KindCron, Command: "/usr/local/bin/omj-agent discover", User: "root", IsAgent: true,
			}},
		},
		{
			name:   "a line with too few fields is unparseable",
			format: userFormat,
			user:   "root",
			lines:  []string{"0 5 * *"},
			want: []Entry{{
				Source: testSource, Raw: "0 5 * *", ScheduleKind: KindCron, User: "root",
				Unparseable: true, Note: "a schedule needs five fields, and this line has 4",
			}},
		},
		{
			name:   "a value outside its field is unparseable",
			format: systemFormat,
			lines:  []string{"70 * * * * root /usr/bin/never-runs"},
			want: []Entry{{
				Source: testSource, Raw: "70 * * * * root /usr/bin/never-runs", ScheduleKind: KindCron,
				Unparseable: true, Note: `the minute "70" is outside 0-59`,
			}},
		},
		{
			name:   "a step that is not a number is unparseable",
			format: userFormat,
			user:   "root",
			lines:  []string{"*/0 * * * * /usr/local/bin/never"},
			want: []Entry{{
				Source: testSource, Raw: "*/0 * * * * /usr/local/bin/never", ScheduleKind: KindCron, User: "root",
				Unparseable: true, Note: `the minute "*/0" steps by "0", which is not a whole number above zero`,
			}},
		},
		{
			name:   "an unknown shorthand is unparseable",
			format: userFormat,
			user:   "root",
			lines:  []string{"@fortnightly /usr/local/bin/sometimes"},
			want: []Entry{{
				Source: testSource, Raw: "@fortnightly /usr/local/bin/sometimes", ScheduleKind: KindCron, User: "root",
				Unparseable: true, Note: `"@fortnightly" is not one of cron's shorthands (@reboot, @yearly, @annually, @monthly, @weekly, @daily, @midnight, @hourly)`,
			}},
		},
		{
			name:   "a system line without a user is unparseable rather than read as one",
			format: systemFormat,
			lines:  []string{"*/5 * * * * /usr/local/bin/no-user-in-this-line"},
			want: []Entry{{
				Source: testSource, Raw: "*/5 * * * * /usr/local/bin/no-user-in-this-line", Schedule: "*/5 * * * *", ScheduleKind: KindCron,
				Unparseable: true, Note: `"/usr/local/bin/no-user-in-this-line" is not a user name, and this file names the user between the schedule and the command`,
			}},
		},
		{
			name:   "a schedule with nothing after it is unparseable",
			format: systemFormat,
			lines:  []string{"17 3 * * * stats"},
			want: []Entry{{
				Source: testSource, Raw: "17 3 * * * stats", Schedule: "17 3 * * *", ScheduleKind: KindCron, User: "stats",
				Unparseable: true, Note: "the line has a schedule but no command",
			}},
		},
		{
			name:   "a line that is not a schedule at all keeps its text",
			format: userFormat,
			user:   "deploy",
			lines:  []string{"this line is not a schedule"},
			want: []Entry{{
				Source: testSource, Raw: "this line is not a schedule", ScheduleKind: KindCron, User: "deploy",
				Unparseable: true, Note: `the minute "this" is neither a number nor a name cron knows`,
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseCrontabLines(tt.format, tt.user, tt.lines...)

			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parsed %d entries:\n got %+v\nwant %+v", len(got), got, tt.want)
			}
		})
	}
}

func TestEnvironmentAssignment(t *testing.T) {
	tests := []struct {
		name      string
		text      string
		wantName  string
		wantValue string
		wantOK    bool
	}{
		{name: "plain", text: "CRON_TZ=UTC", wantName: "CRON_TZ", wantValue: "UTC", wantOK: true},
		{name: "spaces around the equals sign", text: "CRON_TZ = Europe/Lisbon", wantName: "CRON_TZ", wantValue: "Europe/Lisbon", wantOK: true},
		{name: "quoted value", text: `MAILTO="ops@example.com"`, wantName: "MAILTO", wantValue: "ops@example.com", wantOK: true},
		{name: "empty quoted value", text: `MAILTO=""`, wantName: "MAILTO", wantValue: "", wantOK: true},
		{name: "digits after the first character", text: "PATH2=/usr/bin", wantName: "PATH2", wantValue: "/usr/bin", wantOK: true},
		{name: "a schedule is not an assignment", text: "*/5 * * * * root /usr/bin/foo --flag=1", wantOK: false},
		{name: "a name cannot start with a digit", text: "2PATH=/usr/bin", wantOK: false},
		{name: "a line without an equals sign", text: "0 5 * * * /usr/bin/foo", wantOK: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			name, value, ok := environmentAssignment(tt.text)

			if ok != tt.wantOK || name != tt.wantName || value != tt.wantValue {
				t.Errorf("environmentAssignment(%q) = %q, %q, %v, want %q, %q, %v", tt.text, name, value, ok, tt.wantName, tt.wantValue, tt.wantOK)
			}
		})
	}
}

func TestIsCronDName(t *testing.T) {
	tests := []struct {
		name string
		want bool
	}{
		{name: "certbot", want: true},
		{name: "e2scrub_all", want: true},
		{name: "0anacron", want: true},
		{name: "certbot.dpkg-dist", want: false},
		{name: ".hidden", want: false},
		{name: "backup~", want: false},
		{name: "", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isCronDName(tt.name); got != tt.want {
				t.Errorf("isCronDName(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

func TestIsUserName(t *testing.T) {
	tests := []struct {
		name string
		want bool
	}{
		{name: "root", want: true},
		{name: "www-data", want: true},
		{name: "user.name", want: true},
		{name: "/usr/bin/foo", want: false},
		{name: "-root", want: false},
		{name: "a user", want: false},
		{name: "", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isUserName(tt.name); got != tt.want {
				t.Errorf("isUserName(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

func parseCrontabLines(format crontabFormat, user string, lines ...string) []Entry {
	parser := cronParser{source: testSource, format: format, user: user, agentPath: "/usr/local/bin/omj-agent"}

	var entries []Entry

	for _, line := range lines {
		if entry, ok := parser.parse(line); ok {
			entries = append(entries, entry)
		}
	}

	return entries
}
